/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#2a1700',
        'surface-container-low': '#191b22',
        'secondary-container': '#ee9800',
        'on-tertiary-container': '#fffafb',
        'primary-fixed-dim': '#ffb3b6',
        outline: '#ac8889',
        'inverse-on-surface': '#2e3037',
        background: '#111319',
        'surface-dim': '#111319',
        'surface-container': '#1e1f26',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffdada',
        'secondary-fixed': '#ffddb8',
        'surface-tint': '#ffb3b6',
        'on-background': '#e2e2eb',
        'primary-container': '#e11d48',
        'surface-container-lowest': '#0c0e14',
        'on-tertiary': '#3f008e',
        'on-tertiary-fixed-variant': '#5a00c6',
        'error-container': '#93000a',
        tertiary: '#d2bbff',
        'on-surface-variant': '#e5bdbe',
        'on-secondary': '#472a00',
        'surface-container-high': '#282a30',
        'on-secondary-container': '#5b3800',
        secondary: '#ffb95f',
        error: '#ffb4ab',
        'on-secondary-fixed-variant': '#653e00',
        'on-primary-fixed-variant': '#920028',
        'secondary-fixed-dim': '#ffb95f',
        'on-primary-fixed': '#40000c',
        'outline-variant': '#5c3f40',
        'on-primary-container': '#fffaf9',
        'on-primary': '#68001a',
        'on-surface': '#e2e2eb',
        'on-tertiary-fixed': '#25005a',
        'surface-container-highest': '#33343b',
        'tertiary-fixed-dim': '#d2bbff',
        'tertiary-fixed': '#eaddff',
        surface: '#111319',
        'on-error': '#690005',
        'tertiary-container': '#8a4bfb',
        'surface-variant': '#33343b',
        'inverse-surface': '#e2e2eb',
        'inverse-primary': '#be0037',
        primary: '#ffb3b6',
        'surface-bright': '#373940',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1.5rem',
        'margin-mobile': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'gutter-mobile': '0.75rem',
        'space-md': '1rem',
        margin: '2.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
      },
      fontFamily: {
        'headline-lg': ['Plus Jakarta Sans'],
        'headline-xl-mobile': ['Plus Jakarta Sans'],
        'label-caps': ['Inter'],
        'headline-md': ['Plus Jakarta Sans'],
        'display-hero': ['Plus Jakarta Sans'],
        'body-md': ['Inter'],
        'headline-xl': ['Plus Jakarta Sans'],
        'body-lg': ['Inter'],
        'display-hero-mobile': ['Plus Jakarta Sans'],
        'label-md': ['Inter'],
        'body-sm': ['Inter'],
        'title-sm': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'display-hero-mobile': ['34px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-md': ['13px', { lineHeight: '16px', fontWeight: '500' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'title-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
